# Generated by Django 5.0.7 on 2024-07-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=24)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=50)),
                ("long_name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topic_created_by",
                        to="resources.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topic_updated_by",
                        to="resources.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=50)),
                ("long_name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_created_by",
                        to="resources.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_updated_by",
                        to="resources.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=50)),
                ("long_name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "grade_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "elementary",
                                [
                                    ("PK", "pre-K"),
                                    ("KG", "Kindergarten"),
                                    ("1", "First"),
                                    ("2", "Second"),
                                    ("3", "Third"),
                                    ("4", "Forth"),
                                    ("5", "Fifth"),
                                ],
                            ),
                            (
                                "middle",
                                [("6", "Sixth"), ("7", "Seventh"), ("8", "Eighth")],
                            ),
                            ("high", [("9", "Ninth"), ("10", "tenth")]),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "grade_level_min",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "elementary",
                                [
                                    ("PK", "pre-K"),
                                    ("KG", "Kindergarten"),
                                    ("1", "First"),
                                    ("2", "Second"),
                                    ("3", "Third"),
                                    ("4", "Forth"),
                                    ("5", "Fifth"),
                                ],
                            ),
                            (
                                "middle",
                                [("6", "Sixth"), ("7", "Seventh"), ("8", "Eighth")],
                            ),
                            ("high", [("9", "Ninth"), ("10", "tenth")]),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "grade_level_max",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "elementary",
                                [
                                    ("PK", "pre-K"),
                                    ("KG", "Kindergarten"),
                                    ("1", "First"),
                                    ("2", "Second"),
                                    ("3", "Third"),
                                    ("4", "Forth"),
                                    ("5", "Fifth"),
                                ],
                            ),
                            (
                                "middle",
                                [("6", "Sixth"), ("7", "Seventh"), ("8", "Eighth")],
                            ),
                            ("high", [("9", "Ninth"), ("10", "tenth")]),
                        ],
                        max_length=2,
                    ),
                ),
                ("link", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.topic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_created_by",
                        to="resources.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_updated_by",
                        to="resources.user",
                    ),
                ),
            ],
        ),
    ]
