# Generated by Django 5.0.7 on 2024-07-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_alter_topic_created_by_alter_topic_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="link",
            field=models.URLField(),
        ),
    ]
